### ISSUE TITLE
Incorrect query in case when name of the table contains square brackets

### ISSUE THREAD

**Issue by spzSource** [tssoft/TsSoft.Dapper.QueryBuilder#1]
QueryBuilder builds incorrect query in case when name of the table contains square brackets. ([Order] for instance).

Example:
```c#
    [Table("[Order]")]
    public class OrderFetchingCriteria : Criteria
    {
        [Where("Partner", WhereType = WhereType.Eq")]
        public Guid? PartnerId { get; set; }

        public OrderFetchingCriteria()
        {
            QueryType = QueryType.Paginate;
        }
    }
```
```c#
Query query = new QueryBuilder<TCriteria>(criteria).Build();
```
So, query produces following SQL statements:

```SQL
Select [Order].*
 from [Order] 
 WHERE [Order].Partner = @[Order]PartnerId 
...
```
#### Actual result
`@[Order]PartnerId` is not relevant sql parameter. 

#### Expected result
Parameter should be like this `@OrderPartnerId`

**Comment by riberk** [comment]
[nuget package](https://www.nuget.org/packages/TsSoft.Dapper.QueryBuilder) updated

**Comment by spzSource** [comment]
Thanks!
