### ISSUE TITLE
0 as {0} Queries

### ISSUE THREAD

**Issue by iyilm4z** [tssoft/TsSoft.Dapper.QueryBuilder#3]
I do wonder why QueryBuilder builds those codes which are bolded? 

Select Houses.* , 
**0 as SplitOnOwnersId** 
from Houses LEFT JOIN Owners on Owners.Id = Houses.OwnerId WHERE Owners.OwnerName 
Like @OwnersOwnerName

Select Houses.* , 
**0 as SplitOnPersonsHouseId** , 
Persons.*
 from Houses LEFT JOIN Persons on Persons.HouseId = Houses.HouseId

I took a look at this code but i could't get why.

```
if (!string.IsNullOrWhiteSpace(joinClause.Splitter) && criteria.QueryType != QueryType.Sum)
{
     Builder.Select(string.Format("0 as {0}", joinClause.Splitter));                    
}
```

**Comment by spzSource** [comment]
Hi @iyilm4z 
```0 as SplitOnPersonsHouseId ``` is used for splitting and mapping result from query to the appropriate objects. It's like a delimiter which tells dapped what column we need to use to distinguish ```House``` and ```Owner```.

**Comment by spzSource** [comment]
@iyilm4z 

BTW, this is useful for multi-mapping. More info [here](https://github.com/StackExchange/Dapper#multi-mapping).

In some cases it is required to specify by which collumn you want to split your results, like in the example below:

```cs
[Table("Product")]
public class ProductItem
{
    public decimal ProductID { get; set; }        
    public string ProductName { get; set; }
    public string AccountOpened { get; set; }
    public Customer Customer { get; set; }
} 

public class Customer
{
    public decimal CustomerId { get; set; }
    public string CustomerName { get; set; }
}

....
Query query = builder.Build();

....
var item = connection.Query<ProductItem, Customer, ProductItem>(query.Sql,
    (p, c) => { p.Customer = c; return p; }, splitOn: query.SplitOn).First();
```

**Comment by iyilm4z** [comment]
@spzSource Great explanation! Agromnoe spasibo Alexey!
